### ISSUE TITLE
Storage mounts with dynamic configuration

### ISSUE THREAD

**Issue by maou-shonen** [nitrojs/nitro#1161]
## Describe the feature

relates nuxt/nuxt#20195

The examples in the above discussions are fairly common,
maybe provide a function to escape?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Configuration from `nitro.config` and `app.config` is serialized during building we cannot use dynamic configuration from there. I am thinking to support `nitro.storage` from `app.config.ts` to make it possible. 

As a workaround, you can use a runtime plugin to mount in app context using `plugins/storage.ts` (nuxt: `server/plugins/storage.ts`)

```ts
import redis from "unstorage/drivers/redis";

export default defineNitroPlugin(() => {
  const storage = useStorage();
  storage.mount(
    "/redis",
    redis({
      // ... options from runtime config, app config or process.env
    })
  );
});
```

**Comment by mao-shonen** [comment]
If possible, I would still prefer to have some way of preserving process.env.
like this nuxt/nuxt#18910
potentially bad DX if I have many modules and use different default value on different environments.

**Comment by qin-guan** [comment]
Would it be possible to document the temporary workaround as mentioned by @pi0 (https://github.com/unjs/nitro/issues/1161#issuecomment-1511444675) inside Nuxt documentation? 

Would be happy to open a PR for this! Thanks (:

**Comment by pi0** [comment]
PR also welcome for nitro docs to mention workaround in storage section 👍🏼

**Comment by daniandl** [comment]
Sorry for necro but is there a way to do this for the cache system too?
Currently, if I try to mount `cache` in a plugin using pi0's way, i get `ERROR [worker init] already mounted at cache`.

Is the only way here to override every single `defineCachedEventHandler` to use a custom mount point (base)?

**Comment by pi0** [comment]
you might need to call `.unmount()` first.

**Comment by censujiang** [comment]
same question

**Comment by censujiang** [comment]
When I create a plugin using the following code

```ts
import redisDriver from 'unstorage/drivers/redis'
import azureAppConfigurationDriver from 'unstorage/drivers/azure-app-configuration'

export default defineNitroPlugin((nuxtApp) => {
  const storage = useStorage()
  if (useRuntimeConfig().systemRuntimeType == 'azure') {
    storage.unmount('cache')
    const azure = azureAppConfigurationDriver({
      prefix: "default",
      label: "cache",
    })
    storage.mount('cache', azure)
  } else {
    storage.unmount('cache')
    const redis = redisDriver({
      url: "redis://localhost:6379",
    })
    storage.mount('cache', redis)
  }
})
```

The following error occurred

```console
 ERROR  [nuxt] [request error] [unhandled] [500] Cannot access 'nitroApp' before initialization                                                                                                                                          20:03:46  
  at Object.onRequest (/D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:6801:7)
  at Object.handler (/D:/my-nuxt-template/node_modules/h3/dist/index.mjs:1959:21)
  at toNodeHandle (/D:/my-nuxt-template/node_modules/h3/dist/index.mjs:2266:17)
  at callHandle (/D:/my-nuxt-template/node_modules/unenv/runtime/fetch/call.mjs:25:12)
  at ufetch (/D:/my-nuxt-template/node_modules/unenv/runtime/fetch/index.mjs:9:23)
  at Object.localFetch (/D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:6821:39)
  at /D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:3162:36
```

How can I solve this problem?

**Comment by censujiang** [comment]
> When I create a plugin using the following code
> 
> ```ts
> import redisDriver from 'unstorage/drivers/redis'
> import azureAppConfigurationDriver from 'unstorage/drivers/azure-app-configuration'
> 
> export default defineNitroPlugin((nuxtApp) => {
>   const storage = useStorage()
>   if (useRuntimeConfig().systemRuntimeType == 'azure') {
>     storage.unmount('cache')
>     const azure = azureAppConfigurationDriver({
>       prefix: "default",
>       label: "cache",
>     })
>     storage.mount('cache', azure)
>   } else {
>     storage.unmount('cache')
>     const redis = redisDriver({
>       url: "redis://localhost:6379",
>     })
>     storage.mount('cache', redis)
>   }
> })
> ```
> 
> The following error occurred
> 
> ```
>  ERROR  [nuxt] [request error] [unhandled] [500] Cannot access 'nitroApp' before initialization                                                                                                                                          20:03:46  
>   at Object.onRequest (/D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:6801:7)
>   at Object.handler (/D:/my-nuxt-template/node_modules/h3/dist/index.mjs:1959:21)
>   at toNodeHandle (/D:/my-nuxt-template/node_modules/h3/dist/index.mjs:2266:17)
>   at callHandle (/D:/my-nuxt-template/node_modules/unenv/runtime/fetch/call.mjs:25:12)
>   at ufetch (/D:/my-nuxt-template/node_modules/unenv/runtime/fetch/index.mjs:9:23)
>   at Object.localFetch (/D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:6821:39)
>   at /D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:3162:36
> ```
> 
> How can I solve this problem?

After testing, this state will only appear when the database is cache

**Comment by censujiang** [comment]
> > When I create a plugin using the following code
> > ```ts
> > import redisDriver from 'unstorage/drivers/redis'
> > import azureAppConfigurationDriver from 'unstorage/drivers/azure-app-configuration'
> > 
> > export default defineNitroPlugin((nuxtApp) => {
> >   const storage = useStorage()
> >   if (useRuntimeConfig().systemRuntimeType == 'azure') {
> >     storage.unmount('cache')
> >     const azure = azureAppConfigurationDriver({
> >       prefix: "default",
> >       label: "cache",
> >     })
> >     storage.mount('cache', azure)
> >   } else {
> >     storage.unmount('cache')
> >     const redis = redisDriver({
> >       url: "redis://localhost:6379",
> >     })
> >     storage.mount('cache', redis)
> >   }
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The following error occurred
> > ```
> >  ERROR  [nuxt] [request error] [unhandled] [500] Cannot access 'nitroApp' before initialization                                                                                                                                          20:03:46  
> >   at Object.onRequest (/D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:6801:7)
> >   at Object.handler (/D:/my-nuxt-template/node_modules/h3/dist/index.mjs:1959:21)
> >   at toNodeHandle (/D:/my-nuxt-template/node_modules/h3/dist/index.mjs:2266:17)
> >   at callHandle (/D:/my-nuxt-template/node_modules/unenv/runtime/fetch/call.mjs:25:12)
> >   at ufetch (/D:/my-nuxt-template/node_modules/unenv/runtime/fetch/index.mjs:9:23)
> >   at Object.localFetch (/D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:6821:39)
> >   at /D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:3162:36
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How can I solve this problem?
> 
> After testing, this state will only appear when the database is cache

@pi0 I think this is a problem that needs to be solved urgently. Even the most basic ones can't be used. . .

**Comment by 1v33n** [comment]
Any updates on this issue?

**Comment by sadeghi-aa** [comment]
> Sorry for necro but is there a way to do this for the cache system too? Currently, if I try to mount `cache` in a plugin using pi0's way, i get `ERROR [worker init] already mounted at cache`.
> 
> Is the only way here to override every single `defineCachedEventHandler` to use a custom mount point (base)?

I'm trying to set up the cache storage at runtime to use a redis server but I get the same error. Could you please provide your solution? I've tried this so far:

```javascript
import redisDriver from 'unstorage/drivers/redis'

export default defineNitroPlugin(() => {
  const storage = useStorage()

  storage.unmount('cache:')

  const redis = redisDriver({
    url: 'redis://localhost:6380', // To be replaced with the actual redis URL
  })

  storage.mount('cache:', redis)
})
```

**Comment by sadeghi-aa** [comment]
> > Sorry for necro but is there a way to do this for the cache system too? Currently, if I try to mount `cache` in a plugin using pi0's way, i get `ERROR [worker init] already mounted at cache`.
> > Is the only way here to override every single `defineCachedEventHandler` to use a custom mount point (base)?
> 
> I'm trying to set up the cache storage at runtime to use a redis server but I get the same error. Could you please provide your solution? I've tried this so far:
> 
> import redisDriver from 'unstorage/drivers/redis'
> 
> export default defineNitroPlugin(() => {
>   const storage = useStorage()
> 
>   storage.unmount('cache:')
> 
>   const redis = redisDriver({
>     url: 'redis://localhost:6380', // To be replaced with the actual redis URL
>   })
> 
>   storage.mount('cache:', redis)
> })

For anyone encountering this issue in the future, the `unmount` function is a Promise. You have to await it. Spent hours to figure this out xD
