### ISSUE TITLE
Maximum call stack size exceeded  at applyProductionCondition 

### ISSUE THREAD

**Issue by MosheL** [nitrojs/nitro#1263]
### Environment

Node 19.9
nuxt 4.3.4, 4.5.1 withn nitro 2.4.1 and tried more versions of nuxt & nitro.

### Reproduction

How I can debug it without exporting the whole code?

I tried to connect a debugger, I tried to manual change the  `applyProductionCondition`  try/catch  and log the problem.
How I can find the problem in the project?

### Describe the bug

npx nuxi build 

client done OK.

i Building Nitro Server (preset: node-server)                   nitro 18:27:57

 ERROR  RangeError: Maximum call stack size exceeded                 nitro 18:29:36

undefined

 ERROR  Maximum call stack size exceeded                                   18:29:36

  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:713:3)
  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:724:5)
  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:724:5)
  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:724:5)
  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:724:5)
  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:724:5)
  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:724:5)
  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:724:5)
  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:724:5)
  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:724:5)

### Additional context

Nuxt 3.4.3 upgraded  to 3.5.1 (tried to force nuxt/ nuxi 3.4.3 via npm did not help).

How to  start the debug  it?

I tried:
foced a specific version of nitro (2.3.3 last known works, but did not work after `yarn`)
force a specific version of rollup
clear `node_modules` and  revert to old version of the code
upgrade `yarn`
use `npm` and `yarn` (and clean before and after).
connect a debugger 

try use 
` try {
    applyProductionCondition(exports[key]);
	}
	catch(ex) {
	console.log(ex.message +', ' + key  + exports[key].toString())
	}`
to find the  export make the crash

**Comment by pi0** [comment]
This issue had been open for a long time without reproduction. If you still have the same issue and can reproduce it, please feel free to comment and reopen 👍🏼
