### ISSUE TITLE
Proxy breaks on responses without body

### ISSUE THREAD

**Issue by vushe** [nitrojs/nitro#1275]
### Environment

Node: 18.15.0
Nuxt 3.5.0 with Nitro 2.4.1
h3: 1.6.6

### Describe the bug

Somewhat similar with https://github.com/unjs/nitro/issues/1237, but another issue.

Proxy fails (in this particular case when `204 No Content` is responded from API) with following error:
```
"url":"/proxy/customer/change-details?countryCode=FI",
"statusCode":500,
"statusMessage":"",
"message":"Cannot read properties of null (reading 'Symbol(Symbol.asyncIterator)')",
"stack":"<pre><span class=\"stack internal\">at sendProxy (./node_modules/h3/dist/index.mjs:560:38)</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at async Object.handler (./node_modules/h3/dist/index.mjs:1255:19)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1330:7)</span></pre>"
```

In `./node_modules/h3/dist/index.mjs:560:38` we have following:
```js
    for await (const chunk of response.body) {
      event.node.res.write(chunk);
    }
```

So it looks like check for empty `response.body` is missing. Following fixes the issue:
```js
  if (response.body) {
    for await (const chunk of response.body) {
      event.node.res.write(chunk);
    }
  }
```

**Comment by pi0x** [comment]
This does not happen on v3 — proxying an upstream that answers 204 with no body passes the 204 through cleanly.

_Triaged with AI assistance._
