### ISSUE TITLE
Fresh Install Error

### ISSUE THREAD

**Issue by Putnug1122** [nitrojs/nitro#1691]
### Environment

Nodejs : v18.17.1
Nitro : latest
pnpm : 8.6.11

### Reproduction

Just created a new nitro projects (following the docs) and get defineNitroConfig is not defined error

### Describe the bug

When I run pnpm install it's show "defineNitroConfig is not defined"

### Logs

```sh
ReferenceError: defineNitroConfig is not defined
    at /home/deta/Dump/nitro-app/nitro.config.ts:2:16
    at evalModule (/home/deta/Dump/nitro-app/node_modules/.pnpm/jiti@1.19.3/node_modules/jiti/dist/jiti.js:1:255202)
    at Object.jiti (/home/deta/Dump/nitro-app/node_modules/.pnpm/jiti@1.19.3/node_modules/jiti/dist/jiti.js:1:253130)
    at resolveConfig (file:///home/deta/Dump/nitro-app/node_modules/.pnpm/c12@1.4.2/node_modules/c12/dist/index.mjs:280:24)
    at async loadConfig (file:///home/deta/Dump/nitro-app/node_modules/.pnpm/c12@1.4.2/node_modules/c12/dist/index.mjs:116:34)
    at async loadOptions (file:///home/deta/Dump/nitro-app/node_modules/.pnpm/nitropack@2.3.3/node_modules/nitropack/dist/shared/nitro.96034a6e.mjs:3520:30)
    at async createNitro (file:///home/deta/Dump/nitro-app/node_modules/.pnpm/nitropack@2.3.3/node_modules/nitropack/dist/shared/nitro.96034a6e.mjs:3719:19)
    at async main (file:///home/deta/Dump/nitro-app/node_modules/.pnpm/nitropack@2.3.3/node_modules/nitropack/dist/cli.mjs:67:19)
```

**Comment by pi0** [comment]
This issue had been open for a long time without reproduction. If you still have the same issue and can reproduce it, please feel free to comment and reopen 👍🏼 

Usually you need to import `defineNitroConfig` from `nitropack/config`
