### ISSUE TITLE
WebSocket Support Tracker

### ISSUE THREAD

**Issue by pi0** [nitrojs/nitro#2171]
Initial PR: https://github.com/unjs/nitro/pull/2170

Relavant docs:
 - https://h3.unjs.io/guide/websocket
 - https://crossws.unjs.io

# Platform support

- [ ] Dev server
  - [x] Runtime handlers
  - [ ] Dev handlers
- [x] `bun`
- [x] Cloudflare
  - [x] `cloudflare-pages`
  - [x] `cloudflare-module`
  - [x] `cloudflare` (worker)
- [x] Deno
  - [x] `deno-deploy`
  - [x] `deno-server`
- [ ] Node
  - [x] `node-server`
  - [x] `node` via `websocket` export
  - [ ] `node-cluster`
- [x] Vercel

Needs investigation:

- [ ] `aws-lambda`
- [ ] AWS amplify
- [ ] Firebase
- [ ] Netlify
  - [ ] `netlify-edge`
  - [ ] `netlify-lambda`
- [ ] `stormkit`
- [ ] `wnterjs`
- [ ] `zerabur`

**Comment by passionate-bram** [comment]
After reviewing the Netlify documentation, I found no suitable offering that will properly support websocket servers at this time.

1. [Netlify Functions](https://docs.netlify.com/functions/overview/#default-deployment-options) are killed off after 10 seconds. This limit can be increased to 26 seconds if you contact support.
2. [Netlify Edge-Functions](https://docs.netlify.com/edge-functions/limits/) have max 10 seconds of CPU time.
3. [Netlify Background Functions](https://docs.netlify.com/functions/background-functions/) can run for 15 minutes, but they cannot send a response to the request that triggered them.

**Comment by pi0** [comment]
Thanks for your investigation. Re Netlify, i have reached out and waiting for an answer if there is any viable current or future plans.

**Comment by StringKe** [comment]
Is websocket still not available in the current development mode of the latest nuxt?

I try to access /websocket in development mode (pnpm run dev) and it's always connecting.

If I compile and start with `node .output/server/index.mjs` everything works fine.

https://github.com/StringKe/report-nuxt-webscoket

**Comment by pi0** [comment]
@StringKe You need to use `nuxi-nightly`.

**Comment by pi0** [comment]
`uws` requires it's own server preset for Nitro to be supported.

**Comment by StringKe** [comment]
does crossws have an API to proactively close connection?

**Comment by indam1** [comment]
Does nuxt support websocket when deployed on cloudflare pages? Everything is fine on localhost, but on Cloudflare I'm getting only status finished

**Comment by FliPPeDround** [comment]
Hello, I am trying to combine peer-server with my Nuxt application. Unfortunately, it doesn't work as expected. 
reproduction issue in [nuxt/nuxt](https://github.com/nuxt/nuxt/issues/26578)

In the peer-server middleware, `ws` is used to send the WebSocket message
https://github.com/peers/peerjs-server/blob/master/src/services/webSocketServer/index.ts#L59
```ts
import { WebSocketServer as Server } from "ws";

const options: WebSocket.ServerOptions = {
	path: this.path,
	server,
};

this.socketServer = new Server(options);

this.socketServer.on("connection", (socket, req) => {
	this._onSocketConnection(socket, req);
});
```

Currently, Nuxt is unable to listen for web socket connection events as expected

**Comment by meesvrh** [comment]
> Does nuxt support websocket when deployed on cloudflare pages? Everything is fine on localhost, but on Cloudflare I'm getting only status finished

Hi did u manage to get this fixed?

**Comment by pileroniel** [comment]
> Thanks for your investigation. Re Netlify, i have reached out and waiting for an answer if there is any viable current or future plans.

Hi, @pi0  any updates on this from the netlify team?

**Comment by serhalp** [comment]
👋🏼 I'm not aware of any plans to change Netlify's support for WebSockets. However, Server-Sent Events (SSE) work great with Netlify Edge Functions.

**Comment by adamdehaven** [comment]
@pi0 is there an example somewhere that instructs how to set up websockets with the `cloudflare-module` Nitro preset? 

When using [the example from the docs](https://nitro.unjs.io/guide/websocket#usage), if I run locally in Nuxt (via `nuxt dev`) the tabs communicate properly; however, when I build and then run `wrangler dev` there is no communication between separate tabs. 

I can see each `peer` is available (the number is incremented for each connected client if I output on the page) but I can not receive messages between them after calling `subscribe/publish` accordingly.

I see the following note on the [`CrossWS Pub / Sub` page](https://crossws.unjs.io/guide/pubsub):

> Native pub/sub is currently only available for [Bun](https://crossws.unjs.io/adapters/bun), [Node.js (uWebSockets)](https://crossws.unjs.io/adapters/node#uwebsockets) and [Cloudflare (durable objects)](https://crossws.unjs.io/adapters/cloudflare)

but there are no instructions as to how to actually hook it up (here in the Nitro docs) to Cloudflare Durable Objects?

If you can point me in the right direction I can also push up a PR for docs

**Comment by pi0** [comment]
Durable-ojbect support is on the progress (sorry for misleading docs, that section is not released yet)

**Comment by adamdehaven** [comment]
> Durable-ojbect support is on the progress (sorry for misleading docs, that section is not released yet)

😅 Well I feel better that I couldn't get it working now. Tag me if I can help test/implement/document

**Comment by bpbastos** [comment]
Hello, is there a way to access the event similar to defineEventHandler or eventHandler in Nuxt? I'm asking because I'm trying to retrieve a router parameter, and all server utility functions require the event parameter.

**Comment by Barbapapazes** [comment]
> Hello, is there a way to access the event similar to defineEventHandler or eventHandler in Nuxt? I'm asking because I'm trying to retrieve a router parameter, and all server utility functions require the event parameter.

A route parameter from the websocket route? what's your use case?

**Comment by bpbastos** [comment]
I'm trying to create a proxy for Parse Server's LiveQueries and need to pass parameters to initialize the SDK and perform the necessary queries. I'm not sure if this is the best approach, as I'm just starting out with WebSockets.

**Comment by sameignatovich** [comment]
Yeah, if it possible, please: add possibility to read params from url. It's might be useful to authenticate user with one-time/signed token.

Possible solution may be second (or first, ws still experimental feature anyway) argument to `open()` hook

**Comment by AgileInteractive** [comment]
What about platforms not mentioned, (e.g. Azure) are they omitted for any reason?

**Comment by tahirmahmudzade** [comment]
> @pi0 is there an example somewhere that instructs how to set up websockets with the `cloudflare-module` Nitro preset?
> 
> When using [the example from the docs](https://nitro.unjs.io/guide/websocket#usage), if I run locally in Nuxt (via `nuxt dev`) the tabs communicate properly; however, when I build and then run `wrangler dev` there is no communication between separate tabs.
> 
> I can see each `peer` is available (the number is incremented for each connected client if I output on the page) but I can not receive messages between them after calling `subscribe/publish` accordingly.
> 
> I see the following note on the [`CrossWS Pub / Sub` page](https://crossws.unjs.io/guide/pubsub):
> 
> > Native pub/sub is currently only available for [Bun](https://crossws.unjs.io/adapters/bun), [Node.js (uWebSockets)](https://crossws.unjs.io/adapters/node#uwebsockets) and [Cloudflare (durable objects)](https://crossws.unjs.io/adapters/cloudflare)
> 
> but there are no instructions as to how to actually hook it up (here in the Nitro docs) to Cloudflare Durable Objects?
> 
> If you can point me in the right direction I can also push up a PR for docs.
> 
> Alternatively, if you have another (non-experimental) suggestion on how to implement similar messaging, I'd be open to try.

hey, currently i'm also facing the same issue, connections works pretty well in local dev ```nuxt dev```. However can't see incoming data when running with ```wrangler dev```. Any lead on this ?

**Comment by estige** [comment]
> > @pi0Existe algum exemplo em algum lugar que instrua como configurar websockets com a `cloudflare-module`predefinição Nitro?
> > Ao usar [o exemplo da documentação](https://nitro.unjs.io/guide/websocket#usage) , se eu executar localmente no Nuxt (via `nuxt dev`), as guias se comunicam corretamente; no entanto, quando eu compilo e executo, `wrangler dev`não há comunicação entre guias separadas.
> > Posso ver que cada um `peer`está disponível (o número é incrementado para cada cliente conectado se eu exibir na página), mas não consigo receber mensagens entre eles depois de fazer a chamada `subscribe/publish`correspondente.
> > Vejo a seguinte nota na [`CrossWS Pub / Sub`página](https://crossws.unjs.io/guide/pubsub) :
> > > O pub/sub nativo está disponível atualmente apenas para [Bun](https://crossws.unjs.io/adapters/bun) , [Node.js (uWebSockets)](https://crossws.unjs.io/adapters/node#uwebsockets) e [Cloudflare (objetos duráveis)](https://crossws.unjs.io/adapters/cloudflare)
> > 
> > 
> > mas não há instruções sobre como conectá-lo (aqui nos documentos do Nitro) aos Objetos Duráveis ​​do Cloudflare?
> > Se você puder me indicar a direção certa, também posso aumentar o PR dos documentos.
> > Alternativamente, se você tiver outra sugestão (não experimental) sobre como implementar mensagens semelhantes, eu estaria aberto a tentar.
> 
> ei, atualmente também estou enfrentando o mesmo problema, as conexões funcionam muito bem no dev local `nuxt dev`. No entanto, não consigo ver os dados de entrada ao executar com `wrangler dev`. Alguma pista sobre isso?

Any news ?

**Comment by splitwarechef** [comment]
Just tried using this feature in node with nuxt, it seems ws doesn't support sending messages asynchronously.

> WS Implementation

```
export default defineWebSocketHandler({
  open(peer) {
    ready("Connected to peer: ", peer.id);
  },

  async message(peer, message) {
    const config = useRuntimeConfig();
    if (message.text() === "get-data") {
      await $fetch(`${config.public.apiBaseUrl}/frontend-counters`).then(
        peer.send,
      );
    }
  },

  close(peer, event) {
    info(`Peer \`(${peer.id})\` disconnected. Reason: ${event.code}`);
  },

  error(peer, error) {
    fail("An error occured: ", peer.id, error);
  },
});

```

I keep getting this error in preview server

```
[unhandledRejection] TypeError: Cannot read properties of undefined (reading '_internal')
    at send (.output/server/chunks/nitro/nitro.mjs:5266:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async message (.output/server/chunks/routes/api/websocket.mjs:33:7)
ℹ Peer (331f477a-20ca-4ecc-adf7-1ad37d96448e) disconnected. Reason: 1000                                                                                                                            server:ws 9:45:24 AM
[unhandledRejection] TypeError: Cannot read properties of undefined (reading '_internal')
    at send (.output/server/chunks/nitro/nitro.mjs:5266:10)
```
And some times the dev server doesn't start

> Meta

The preview server is `node-server`, on a mac, with node v20.19 (also tested on node 22)

**Comment by pi0** [comment]
@splitwarechef Please consider sharing a minimal reproduction with nitro  🙏🏼

**Comment by splitwarechef** [comment]
See here: https://stackblitz.com/~/github.com/splitwarechef/test-nitro-websocket

Absolute paths don't work on stackblitz so I suggest you try this on your local instead.

**Comment by pi0** [comment]
Thanks for reproduction @splitwarechef 🙏🏼 (please consider using nitro only reproductions in the future not nuxt and also use new issues  )

Issue is that you are calling peer method with wrong context:

```diff
---       await $fetch(`/api/counter`).then(peer.send);
+++       await $fetch(`/api/counter`).then(message => peer.send(message));
```

**Comment by adamdehaven** [comment]
Any idea when the `cloudflare-durable` preset might be ready for production (and docs)? I'd love to cook something up in my production app 👨🏼‍🍳

**Comment by splitwarechef** [comment]
> Thanks for reproduction [@splitwarechef](https://github.com/splitwarechef) 🙏🏼 (please consider using nitro only reproductions in the future not nuxt and also use new issues )
> 
> Issue is that you are calling peer method with wrong context:
> 
> ---       await $fetch(`/api/counter`).then(peer.send);
> +++       await $fetch(`/api/counter`).then(message => peer.send(message));

Thank you @pi0. Also, noted!.

**Comment by Q16solver** [comment]
Not exactly standard, but I'm using a bastardized version in server middleware to wrap the nuxt node server to create a Websocket that can be integrated with trpc. I was wondering if there were any plans to be able to let us define the server it uses e.g. if I want to switch completely to uwebsockets etc and integrate with the trpc uwebsockets package, just throwing this out there in case there are other options I'm not aware of

```ts
import type { CreateWSSContextFnOptions } from "@trpc/server/adapters/ws";
import type { Server } from "node:http";

import { getSynchronizedFunction } from "#shared/util/getSynchronizedFunction";
import { createCallerFactory } from "@@/server/trpc";
import { createContext } from "@@/server/trpc/context";
import { trpcRouter } from "@@/server/trpc/routers";
import { userRouter } from "@@/server/trpc/routers/user";
import { applyWSSHandler } from "@trpc/server/adapters/ws";
import { WebSocketServer } from "ws";

export default defineEventHandler((event) => {
  if (global.websocketServer) return;

  const server =
    event.node.res.socket && "server" in event.node.res.socket ? (event.node.res.socket.server as Server) : null;
  if (!server) return;

  const wss = new WebSocketServer({ server });
  const handler = applyWSSHandler({
    createContext,
    keepAlive: { enabled: true },
    router: trpcRouter,
    wss,
  });
  const createCaller = createCallerFactory(userRouter);

  wss.on(
    "connection",
    getSynchronizedFunction(async (ws, req) => {
      const context = createContext({ req, res: ws } as CreateWSSContextFnOptions);
      const caller = createCaller(context);
      await caller.connect();
      console.log(`Connection opened, client size: ${wss.clients.size}`);
      ws.once(
        "close",
        getSynchronizedFunction(async () => {
          await caller.disconnect();
          console.log(`Connection closed, client size: ${wss.clients.size}`);
        }),
      );
    }),
  );
  process.on("SIGTERM", () => {
    handler.broadcastReconnectNotification();
    wss.close();
  });

  console.log("WebSocket Server is listening");
  global.websocketServer = wss;
});
```

**Comment by DannyVogel** [comment]
Just in case it helps to know, Im playing around with a Nuxt chat app using websockets and deployed to [Render](https://render.com/) without issues. Using the $7 starter instance type. If you need more details I can provide them but for now its a pretty basic app.

**Comment by mickmister** [comment]
Anyone know the implications of this todo comment? Maybe it's functional but not yet fully customizable through nitro APIs?

https://github.com/nitrojs/nitro/blob/main/src/presets/cloudflare/runtime/cloudflare-durable.ts#L30-L37

**Comment by pi0** [comment]
WebSocket is not supported yet in v3 that todo is one of them. I have it in my next (or other) week plan for v3 support.

**Comment by nove1398** [comment]
> WebSocket is not supported yet in v3 that todo is one of them. I have it in my next (or other) week plan for v3 support.

Is there another plugin to use in v3 while this is being worked on?

**Comment by pi0** [comment]
Websocket support landing for v3: https://github.com/nitrojs/nitro/pull/3766

**Comment by Mustached-Maniac** [comment]
Any luck with getting the examples updated for cloudflare durable-object? Hitting the same wall as the comments from the last year.  Works fine in localhost (likely due to persisting the map between server and client), but not working in production.  

Use-case is I have a broadcaster "room" where "viewers" and "alerts" both connect.  Certain events get sent to the connected alerts, and others to the viewers.

Thanks in advance!
