### ISSUE TITLE
`reader.getReader is not a function` when redirecting in API Route

### ISSUE THREAD

**Issue by Jhinger** [nitrojs/nitro#2613]
### Environment

`Node`: 20.13.1
`Nitro`: Nightly v2.10.0-28672747.a8234d3b
`Nitro Preset`: aws-lambda-streaming

### Reproduction

Min reproduction using SST: https://github.com/Jhinger/nitro-err

### Describe the bug

Trying to return a redirect from an API route in SolidStart results in the error in the logs below. Not doing anything special in the api route itself:

```
export function GET(event: APIEvent) {
  const url = new URL("https://github.com/Jhinger")
  return sendRedirect(event.nativeEvent, url.toString());
}
```

### Additional context

I am using sendRedirect from vinxi/http in the api route, however Response.redirect had the same effect.

### Logs

```sh
{
    "errorType": "TypeError",
    "errorMessage": "reader.getReader is not a function",
    "stack": [
        "TypeError: reader.getReader is not a function",
        "    at Runtime.handler (file:///var/task/chunks/nitro/nitro.mjs:6577:39)",
        "    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26)"
    ]
}
```

**Comment by pi0** [comment]
Sorry for late answerr.

Do you have a chance to test with latest Nitro v3?

**Comment by pi0x** [comment]
Fixed in v3 — the aws-lambda streaming entry now hands the response to srvx (https://github.com/nitrojs/nitro/pull/4056), and both `redirect()` and `Response.redirect()` return a 302 without the `getReader` error when I ran the built handler against a Lambda event.

_Triaged with AI assistance._
