### ISSUE TITLE
Imported package bug

### ISSUE THREAD

**Issue by NamesMT** [nitrojs/nitro#2629]
### Environment

Stackblitz

### Reproduction

https://stackblitz.com/edit/github-p8gz48?file=server%2Froutes%2Findex.ts

### Describe the bug

In normal application and Nuxt client, `nano-memoize` could be imported and use as is (like it's type definition)
In Nitro / Nuxt prerendering, `nano-memoize` returns an import object and could only be used as `.default`

### Logs

```sh
✔ Nitro Server built in 655 ms                                 nitro 9:30:21 AM
mA
a1721529022717
a1721529022717
a1721529022717
mB
[nitro] [request error] [unhandled] _file_home_projects_qgnirbakry_github_node_modules_nano_memoize_dist_nano_memoize_js.default is not a function
  at Object.eval [as handler] (./.nitro/dev/index.mjs:883:106)  
  at async Object.eval [as handler] (./node_modules/h3/dist/index.mjs:2100:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2391:7)
```

**Comment by pi0x** [comment]
Fixed in v3 — default-importing a CJS package whose `module.exports` is a function gives you the function itself in dev, prerender and the built server, no `.default` needed.

_Triaged with AI assistance._
