### ISSUE TITLE
Cloudflare Pages build fails. Cannot resolve "unenv/runtime/node/process/index/"

### ISSUE THREAD

**Issue by ryoid** [nitrojs/nitro#2631]
### Environment

- `nitropack@2.9.7`
- `readable-stream@4.4.0`

### Reproduction

Run build in [Stackblitz](https://stackblitz.com/~/github.com/ryoid/nitro-cfpages-unenv-repo)

Made from starter template and adding `readable-stream`

### Describe the bug

Unable to build for Cloudflare Pages with `readable-stream` 

### Additional context

Related Issues
- https://github.com/unjs/nitro/issues/1821

### Logs

```sh
[12:58:23 AM]  ERROR  Cannot resolve "unenv/runtime/node/process/index/" from "/home/ryoid/nitro-cfpages-unenv-repo/node_modules/.pnpm/readable-stream@4.4.0/node_modules/readable-stream/lib/internal/streams/pipeline.js" and externals are not allowed!

  at Object.resolveId (node_modules/.pnpm/nitropack@2.9.7/node_modules/nitropack/dist/nitro.mjs:2003:17)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.19.0/node_modules/rollup/dist/es/shared/node-entry.js:19733:28)
  at async resolveId (node_modules/.pnpm/rollup@4.19.0/node_modules/rollup/dist/es/shared/node-entry.js:18414:26)
  at async ModuleLoader.resolveId (node_modules/.pnpm/rollup@4.19.0/node_modules/rollup/dist/es/shared/node-entry.js:18817:15)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.19.0/node_modules/rollup/dist/es/shared/node-entry.js:19733:28)
  at async resolveId (node_modules/.pnpm/rollup@4.19.0/node_modules/rollup/dist/es/shared/node-entry.js:18414:26)
  at async ModuleLoader.resolveId (node_modules/.pnpm/rollup@4.19.0/node_modules/rollup/dist/es/shared/node-entry.js:18817:15)
  at async eval (node_modules/.pnpm/@rollup+plugin-commonjs@25.0.8_rollup@4.19.0/node_modules/@rollup/plugin-commonjs/dist/es/index.js:800:16)
  at async eval (node_modules/.pnpm/@rollup+plugin-commonjs@25.0.8_rollup@4.19.0/node_modules/@rollup/plugin-commonjs/dist/es/index.js:792:32)
```

**Comment by ryoid** [comment]
Upon some tinkering it seems like the issue is because [the library use `require('process/')`](https://github.com/nodejs/readable-stream/blob/a2e9aedf4aeee4a5e4d8efcb175edb67e2817eaa/lib/internal/streams/from.js#L5), patching it to `require('process')` without the `/` successfully builds.

**Comment by Dmytro-Tihunov** [comment]
hey, have you managed fix it?

**Comment by danielroe** [comment]
Came across this as well in a dependency with this fix:

```ts
export default defineNuxtConfig({
  alias: {
    'buffer/': 'buffer/',
    'string_decoder/': 'string_decoder/',
    'process/': 'process/',
  }
})
```

**Comment by pi0** [comment]
`<name>/` imports often are intentional by libraries to prefer npm versions. We need to add aliases by care to unenv considering subpaths (like `/index.js`) are also available.

unenv v2 adoption specially for nitro+cf is totally blocked currently..
