### ISSUE TITLE
Unable to dynamically add a driver for a storage named `cache` in a plugin

### ISSUE THREAD

**Issue by censujiang** [nitrojs/nitro#2674]
### Environment

- Nitro: latest
- Node: 20

### Reproduction

[https://stackblitz.com/edit/github-sbrgxd?file=server%2Fplugins%2Fstorage.ts](https://stackblitz.com/edit/github-sbrgxd?file=server%2Fplugins%2Fstorage.ts)

### Describe the bug

As the title indicates, as long as the driver name is cache, an error will occur during the build or dev.

[https://github.com/unjs/nitro/issues/1161#issuecomment-2295248527](https://github.com/unjs/nitro/issues/1161#issuecomment-2295248527)

### Additional context

The problem occurs in the build phase of my Nuxt App, but not in the dev phase of the Nitro copy I provided

### Logs

```sh
ERROR  [nuxt] [request error] [unhandled] [500] Cannot access 'nitroApp' before initialization                                                                                                                                          20:03:46  
  at Object.onRequest (/D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:6801:7)
  at Object.handler (/D:/my-nuxt-template/node_modules/h3/dist/index.mjs:1959:21)
  at toNodeHandle (/D:/my-nuxt-template/node_modules/h3/dist/index.mjs:2266:17)
  at callHandle (/D:/my-nuxt-template/node_modules/unenv/runtime/fetch/call.mjs:25:12)
  at ufetch (/D:/my-nuxt-template/node_modules/unenv/runtime/fetch/index.mjs:9:23)
  at Object.localFetch (/D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:6821:39)
  at /D:/my-nuxt-template/.nuxt/prerender/chunks/runtime.mjs:3162:36
`
```

**Comment by censujiang** [comment]
key code:
```ts
import redisDriver from 'unstorage/drivers/redis'
import azureAppConfigurationDriver from 'unstorage/drivers/azure-app-configuration'

export default defineNitroPlugin((nuxtApp) => {
  const storage = useStorage()
  if (useRuntimeConfig().systemRuntimeType == 'azure') {
    storage.unmount('cache')
    const azure = azureAppConfigurationDriver({
      prefix: "default",
      label: "cache",
    })
    storage.mount('cache', azure)
  } else {
    storage.unmount('cache')
    const redis = redisDriver({
      url: "redis://localhost:6379",
    })
    storage.mount('cache', redis)
  }
})
```

**Comment by sandros94** [comment]
I've just noticed that both `cache` and `CACHE` exist, and the second one does work. But have no clue what the difference are, nor why it works.

PS: in development I also had to create a custom driver, since by default the cache driver points to the current fs in dev.

**Comment by pi0x** [comment]
Fixed in v3 — remounting the `cache` storage from a plugin works in dev, prerender and the built server, no 'Cannot access nitroApp before initialization'.

_Triaged with AI assistance._
