### ISSUE TITLE
bug: manipulating cookies in the error hook gives the error `Cannot set headers after they are sent to the client`

### ISSUE THREAD

**Issue by kiki-kanri** [nitrojs/nitro#2771]
### Environment

Node.js: 18.20.3
Nitropack: 2.9.7

### Reproduction

https://stackblitz.com/edit/github-dyj94s

### Describe the bug

I created a plugin and set up an error hook, in the error hook I return a promise and use setTimeout to execute resolve, simulating the situation of awaiting a promise (possibly performing redis operations, etc).

However, it seems that when executing the error hook, the response headers were sent directly without waiting for the hook to finish executing, which resulted in a `Cannot set headers after they are sent to the client` error in the setCookie in the setTimeout.

I don't know if this is intentional or if it's a hookable/h3 package error, but since I'm writing a session package, I need to handle session changes as well when the error occurs. Or am I using it incorrectly?

I will provide additional information if needed. Thank you.

### Logs

```sh
handler false
promise false
timeout true
[nitro] [uncaughtException] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at __node_internal_captureLargerStackTrace2 (https://githubdyj94s-cjd3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:5335)
    at new NodeError (https://githubdyj94s-cjd3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:4149)
    at ServerResponse.setHeader (https://githubdyj94s-cjd3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:6:8796)
    at Module.setCookie (file:///home/projects/github-dyj94s/node_modules/h3/dist/index.mjs:734:18)
    at Timeout.eval [as _onTimeout] (file:///home/projects/github-dyj94s/.nitro/dev/index.mjs:693:74)
    at https://githubdyj94s-cjd3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:246:4692 {
  code: 'ERR_HTTP_HEADERS_SENT'
```

**Comment by cjpearson** [comment]
I've run into this as well. The `error` hooks is different from the `beforeResponse` and `afterResponse` hook in that it is called in parallel and not awaited. If your hook handler is asynchronous the response will have been sent before your function finishes. 

One alternative may be to use `beforeResponse` and check for an error response, but that currently does not work for all errors. https://github.com/nitrojs/nitro/issues/3254

**Comment by kiki-kanri** [comment]
> 我也碰到過這種情況。 hooks`error`與`beforeResponse`and `afterResponse`hook 的不同之處在於它是並行調用而不是等待。如果您的鉤子處理程序是非同步的，則回應將在您的函數完成之前發送。
> 
> 一種替代方法可能是使用`beforeResponse`並檢查錯誤回應，但目前這並不適用於所有錯誤。[#3254](https://github.com/nitrojs/nitro/issues/3254)

I switched to using the error handler file to handle the error, which overwrote the default error page/response, but at least it did what I wanted at the time.
