### ISSUE TITLE
Running node-cluster preset build throwing EADDRINUSE errors

### ISSUE THREAD

**Issue by aisteneciunaitevalantic** [nitrojs/nitro#2892]
### Environment

Node Version: v18.20.3
Nitro Version: 2.10.4

### Reproduction

https://stackblitz.com/edit/github-mrhh35?file=nitro.config.ts

```
> npm run build
> npm run preview
```

### Describe the bug

Running application with preset 'node-cluster' is throwing EADDRINUSE errors

### Additional context

No such issue in v2.9.7

### Logs

```sh
[nitro] [uncaughtException] Error: bind EADDRINUSE null:3000
    at __node_internal_captureLargerStackTrace2 (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:5335)
    at __node_internal_exceptionWithHostPort2 (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:7017)
    at listenOnPrimaryHandle (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:285:12098)
    at rr (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:55:2291)
    at Worker.<anonymous> (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:55:2716)
    at _0x54dcec.onInternalMessage (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:59:458)
    at _0x54dcec.emit (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:30:11015)
    at emit (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:52:6956)
    at processTicksAndRejections (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:192:1093)
    at https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/blitz.d3acb9e1.js:40:198427
    at _0x40724c (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/blitz.d3acb9e1.js:40:198508)
    at _0x323f12 (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/blitz.d3acb9e1.js:40:508059)
    at https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/blitz.d3acb9e1.js:40:508836
    at Array.forEach (<anonymous>)
    at _0x325fd3 (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/blitz.d3acb9e1.js:40:508824)
    at Map.forEach (<anonymous>)
    at _0x26b4f2 (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/blitz.d3acb9e1.js:40:508453)
    at _0x2934c6 (https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/blitz.d3acb9e1.js:40:507451)
    at https://qgnirvpgrqgithub-iuqv.w-credentialless-staticblitz.com/blitz.d3acb9e1.js:40:507618 {
  errno: -48,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 3000
}
```

**Comment by OskarLebuda** [comment]
Probably, the problem lies here:  
https://github.com/nitrojs/nitro/blob/v2/src/presets/node/runtime/node-server.ts#L32  

The code with `server` should be exported as a `main` (or similarly named) function.  
After a simple change to `node-server.ts`:  

```typescript
export const main = async () => {
  // all code here
};
```

Then, `node-cluster.ts` should update the import in the `runWorker` function:  

```typescript
function runWorker() {
  import("./node-server")
    .then((server) => {
      server.main();
    })
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}
```

**Result:**  
![image](https://github.com/user-attachments/assets/402a2b63-7c64-4ee7-b19e-815b75fdb25c)

I've created a PR for this fix: https://github.com/nitrojs/nitro/pull/2893

**Comment by pi0** [comment]
Thanks for report. this issue shoulld be fixed in the [nightly channel](https://nitro.build/guide/nightly).

**Comment by Zae** [comment]
Any idea when we can expect this fix in nuxt stable? Right now node_cluser mode is totally broken in nuxt > 3.13

**Comment by pi0** [comment]
You can pin `nitropack` only to latest nightly build with Nuxt.

**Comment by Zae** [comment]
Hi @pi0 , using the nightly build is not really a fix for us in production, is there a way to get this fix into stable?

**Comment by pi0** [comment]
I plan a minor shortly but the pinned nightly release is **exactly identical** to normal releases in terms of stability.

**Comment by Zae** [comment]
Thank you Pooya, looking forward to it!
