### ISSUE TITLE
cloudflare-pages preset: 500 Cannot read properties of undefined (reading 'userAgent')

### ISSUE THREAD

**Issue by Velka-DEV** [nitrojs/nitro#2962]
### Environment

Nuxt Version: `3.15.0` (This problem was already present before upgrade to 3.15 so it's unlikely a problem related to Vite 6)
Nitro Version: `2.10.4`

`packages.json`:

```json
{
    "name": "nuxt-app",
    "private": true,
    "type": "module",
    "scripts": {
        "build": "nuxt build",
        "dev": "nuxt dev",
        "generate": "nuxt generate",
        "preview": "nuxt preview",
        "postinstall": "nuxt prepare",
        "lint": "eslint .",
        "lint:fix": "eslint . --fix",
        "format": "prettier --write .",
        "prepare": "husky"
    },
    "dependencies": {
        "@internationalized/date": "^3.6.0",
        "@nuxt/eslint": "^0.7.4",
        "@nuxt/fonts": "^0.10.3",
        "@nuxtjs/color-mode": "^3.5.2",
        "@nuxtjs/i18n": "^9.1.1",
        "@pinia/nuxt": "^0.9.0",
        "@unovis/ts": "^1.5.0",
        "@unovis/vue": "^1.5.0",
        "@vee-validate/nuxt": "^4.15.0",
        "@vee-validate/zod": "^4.15.0",
        "class-variance-authority": "^0.7.1",
        "clsx": "^2.1.1",
        "lucide-vue-next": "^0.446.0",
        "nuxt": "^3.15.0",
        "nuxt-auth-utils": "^0.5.7",
        "nuxt-lucide-icons": "^1.0.5",
        "@radix-icons/vue": "^1.0.0",
        "pinia": "^2.3.0",
        "popover": "^2.4.1",
        "radix-vue": "^1.9.11",
        "shadcn-nuxt": "^0.11.3",
        "tailwind-merge": "^2.6.0",
        "tailwindcss-animate": "^1.0.7",
        "vee-validate": "^4.15.0",
        "vue": "latest",
        "vue-router": "latest",
        "vue-sonner": "^1.3.0",
        "wrangler": "^3.99.0",
        "zod": "^3.24.1"
    },
    "devDependencies": {
        "@commitlint/cli": "^19.6.1",
        "@commitlint/config-conventional": "^19.6.0",
        "@nuxtjs/tailwindcss": "^6.12.2",
        "@vue/devtools-api": "^7.6.8",
        "@vueuse/core": "^11.3.0",
        "@vueuse/nuxt": "^11.3.0",
        "husky": "^9.1.7",
        "prettier": "^3.4.2",
        "prettier-plugin-tailwindcss": "^0.6.9",
        "typescript": "^5.7.2"
    }
}
```

Nuxt modules:
```json
[
      "@nuxtjs/tailwindcss",
      "shadcn-nuxt",
      "@nuxt/eslint",
      "@nuxtjs/color-mode",
      "@nuxtjs/i18n",
      "nuxt-lucide-icons",
      "@vueuse/nuxt",
      "@pinia/nuxt",
      "@nuxt/fonts",
      "@vee-validate/nuxt",
      "nuxt-auth-utils",
  ],
  ```

### Reproduction

Actually unable to reproduce the problem ourself.

### Describe the bug

When we develop or build on our local environments with the default Nitro preset, there is no problem.

The problem occurs when we are deploying to our Cloudflare Pages environments, we get this weird Nuxt error message:

`500 Cannot read properties of undefined (reading 'userAgent')`

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/e4dcae85-1d35-4380-bd8a-029dc0f13e4c" />

The error message itself is not really helpful, we double-checked that the problem is actually not directly in our codebase and so we quickly assumed that this problem might be caused by one of our modules that is not compatible with this preset. 

So I enabled and disabled individually each module to find out which one was causing the problem and we are particularly surprised that if we disable  `shadcn-nuxt` it actually removes the error message (along with breaking our entire UI).

So it is, we have our cause ... but no, actually when I tried to create a reproduction repo I was unable to reproduce the bug, even tried to add every single component that shadcn had to offer, and still nothing.

So here we are, seeking help, we do know that creating issue without providing a reproduction is quite hard but we are actually not able to create one (sorry for that).

### Additional context

Actually something might lead us to think that the problem may occur during some "initialization" phase as when running in the cloudflare instance the problem occur at each page refresh but on local it only appear to occur on the first page load.

### Logs

```sh
[node-fetch-native] Node.js compatible build of `node-fetch-native` is being used in a non-Node.js environment. Please make sure you are using proper export conditions or report this issue to https://github.com/unjs/node-fetch-native. You can set `process.env.DISABLE_NODE_FETCH_NATIVE_WARN` to disable this warning.
ji @ server.mjs:1
.wrangler/tmp/pages-UHi7se/chunks/build/server.mjs @ server.mjs:1
__init @ 93sls1dcev8.js:12
(anonymous) @ renderer.mjs:1
Promise.then
(anonymous) @ renderer.mjs:1
await in (anonymous)
(anonymous) @ renderer.mjs:1
(anonymous) @ renderer.mjs:1
(anonymous) @ nitro.mjs:1
await in (anonymous)
(anonymous) @ nitro.mjs:1
Promise.then
(anonymous) @ nitro.mjs:1
(anonymous) @ nitro.mjs:1
(anonymous) @ nitro.mjs:1
await in (anonymous)
(anonymous) @ nitro.mjs:1
o11 @ nitro.mjs:1
(anonymous) @ nitro.mjs:1
localFetch @ nitro.mjs:1
fetch @ nitro.mjs:1
fetch @ pages-dev-pipeline.ts:26
fetchDispatcher @ middleware-loader.entry.ts:54
__facade_invokeChain__ @ common.ts:53
next @ common.ts:50
jsonError @ middleware-miniflare3-json-error.ts:22
__facade_invokeChain__ @ common.ts:53
next @ common.ts:50
drainBody @ middleware-ensure-req-body-drained.ts:5
__facade_invokeChain__ @ common.ts:53
__facade_invoke__ @ common.ts:63
fetch @ middleware-loader.entry.ts:70

A promise rejection was handled asynchronously. This warning occurs when attaching a catch handler to a promise after it rejected. (rejection #3)

server.mjs:1 TypeError: Cannot read properties of undefined (reading 'userAgent')
    at index-BSsn-Qih.mjs:1:22814
    at .wrangler/tmp/pages-UHi7se/chunks/build/index-BSsn-Qih.mjs (index-BSsn-Qih.mjs:1:30589)
    at __init (93sls1dcev8.js:12:59)
    at server.mjs:1:196566
triggerError @ server.mjs:1
(anonymous) @ server.mjs:1
Promise.catch
pushWithRedirect @ server.mjs:1
push @ server.mjs:1
(anonymous) @ server.mjs:1
executeAsync @ server.mjs:1
setup @ server.mjs:1
(anonymous) @ server.mjs:1
fn @ server.mjs:1
callAsync @ nitro.mjs:1
(anonymous) @ server.mjs:1
runWithContext @ renderer.mjs:1
callWithNuxt @ server.mjs:1
(anonymous) @ server.mjs:1
run @ renderer.mjs:1
runWithContext @ server.mjs:1
(anonymous) @ server.mjs:1
executePlugin @ server.mjs:1
(anonymous) @ server.mjs:1
await in (anonymous)
Up @ server.mjs:1
default @ server.mjs:1
renderToString @ renderer.mjs:1
await in renderToString
(anonymous) @ renderer.mjs:1
await in (anonymous)
(anonymous) @ nitro.mjs:1
await in (anonymous)
(anonymous) @ nitro.mjs:1
(anonymous) @ nitro.mjs:1
(anonymous) @ nitro.mjs:1
await in (anonymous)
(anonymous) @ nitro.mjs:1
o11 @ nitro.mjs:1
(anonymous) @ nitro.mjs:1
localFetch @ nitro.mjs:1
fetch @ nitro.mjs:1
fetch @ pages-dev-pipeline.ts:26
fetchDispatcher @ middleware-loader.entry.ts:54
__facade_invokeChain__ @ common.ts:53
next @ common.ts:50
jsonError @ middleware-miniflare3-json-error.ts:22
__facade_invokeChain__ @ common.ts:53
next @ common.ts:50
drainBody @ middleware-ensure-req-body-drained.ts:5
__facade_invokeChain__ @ common.ts:53
__facade_invoke__ @ common.ts:63
fetch @ middleware-loader.entry.ts:70

A promise rejection was handled asynchronously. This warning occurs when attaching a catch handler to a promise after it rejected. (rejection #4)
```

**Comment by pi0** [comment]
It doesn't look like a direct Nitro issue but Node.js incompatibility added by Nuxt/that specific module.

Please consider reporting this issue to Nuxt or [shadcn-vue](https://github.com/unovue/shadcn-vue) with a minimal reproduction. (feel free to ping me if could help).
